import z from "zod";
import { Status, TranscribeOutput } from "./schema";
export declare const Warm: z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"warm">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        stt: z.ZodOptional<z.ZodBoolean>;
        tts: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strict>;
}, z.core.$strict>;
export declare const Stat: z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"status">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
    }, z.core.$strict>;
}, z.core.$strict>;
export declare const Transcribe: z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"transcribe">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        path: z.ZodString;
        language: z.ZodOptional<z.ZodString>;
        diarization: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strict>;
}, z.core.$strict>;
export declare const Synthesize: z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"synthesize">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        text: z.ZodString;
        preset: z.ZodOptional<z.ZodString>;
        mode: z.ZodOptional<z.ZodEnum<{
            auto: "auto";
            clone: "clone";
            design: "design";
        }>>;
        ref_audio_path: z.ZodOptional<z.ZodString>;
        ref_text: z.ZodOptional<z.ZodString>;
        instruct: z.ZodOptional<z.ZodString>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
        language: z.ZodOptional<z.ZodString>;
        speed: z.ZodOptional<z.ZodNumber>;
        duration: z.ZodOptional<z.ZodNumber>;
        num_step: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strict>;
}, z.core.$strict>;
export declare const Req: z.ZodDiscriminatedUnion<[z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"warm">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        stt: z.ZodOptional<z.ZodBoolean>;
        tts: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strict>;
}, z.core.$strict>, z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"status">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
    }, z.core.$strict>;
}, z.core.$strict>, z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"transcribe">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        path: z.ZodString;
        language: z.ZodOptional<z.ZodString>;
        diarization: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strict>;
}, z.core.$strict>, z.ZodObject<{
    id: z.ZodString;
    cmd: z.ZodLiteral<"synthesize">;
    input: z.ZodObject<{
        cfg: z.ZodObject<{
            runtime: z.ZodObject<{
                enabled: z.ZodBoolean;
                python: z.ZodString;
                device: z.ZodEnum<{
                    auto: "auto";
                    cpu: "cpu";
                    cuda: "cuda";
                    mps: "mps";
                }>;
                dtype: z.ZodEnum<{
                    auto: "auto";
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                install_on_demand: z.ZodBoolean;
                hf_token: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>;
            stt: z.ZodObject<{
                provider: z.ZodLiteral<"whisperx">;
                model: z.ZodString;
                language: z.ZodString;
                timestamps: z.ZodEnum<{
                    none: "none";
                    segment: "segment";
                    word: "word";
                }>;
                diarization: z.ZodBoolean;
                vad: z.ZodBoolean;
                compute_type: z.ZodEnum<{
                    float16: "float16";
                    float32: "float32";
                    int8: "int8";
                }>;
                batch_size: z.ZodNumber;
                beam_size: z.ZodNumber;
            }, z.core.$strict>;
            tts: z.ZodObject<{
                provider: z.ZodLiteral<"omnivoice">;
                default_preset: z.ZodOptional<z.ZodString>;
                presets: z.ZodArray<z.ZodObject<{
                    id: z.ZodString;
                    name: z.ZodString;
                    mode: z.ZodEnum<{
                        auto: "auto";
                        clone: "clone";
                        design: "design";
                    }>;
                    ref_audio_path: z.ZodOptional<z.ZodString>;
                    ref_text: z.ZodOptional<z.ZodString>;
                    instruct: z.ZodOptional<z.ZodString>;
                    design: z.ZodOptional<z.ZodObject<{
                        gender: z.ZodOptional<z.ZodString>;
                        age: z.ZodOptional<z.ZodString>;
                        pitch: z.ZodOptional<z.ZodString>;
                        style: z.ZodOptional<z.ZodString>;
                        english_accent: z.ZodOptional<z.ZodString>;
                        chinese_dialect: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>;
                    tags: z.ZodOptional<z.ZodArray<z.ZodEnum<{
                        "[confirmation-en]": "[confirmation-en]";
                        "[dissatisfaction-hnn]": "[dissatisfaction-hnn]";
                        "[laughter]": "[laughter]";
                        "[question-ah]": "[question-ah]";
                        "[question-ei]": "[question-ei]";
                        "[question-en]": "[question-en]";
                        "[question-oh]": "[question-oh]";
                        "[question-yi]": "[question-yi]";
                        "[sigh]": "[sigh]";
                        "[surprise-ah]": "[surprise-ah]";
                        "[surprise-oh]": "[surprise-oh]";
                        "[surprise-wa]": "[surprise-wa]";
                        "[surprise-yo]": "[surprise-yo]";
                    }>>>;
                    language: z.ZodOptional<z.ZodString>;
                    speed: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strict>>;
                live: z.ZodBoolean;
                autoplay: z.ZodBoolean;
                chunking: z.ZodEnum<{
                    sentence: "sentence";
                }>;
                stop_on_interrupt: z.ZodBoolean;
                strip_markdown: z.ZodBoolean;
                speed: z.ZodNumber;
                duration: z.ZodOptional<z.ZodNumber>;
                num_step: z.ZodNumber;
            }, z.core.$strict>;
        }, z.core.$strict>;
        text: z.ZodString;
        preset: z.ZodOptional<z.ZodString>;
        mode: z.ZodOptional<z.ZodEnum<{
            auto: "auto";
            clone: "clone";
            design: "design";
        }>>;
        ref_audio_path: z.ZodOptional<z.ZodString>;
        ref_text: z.ZodOptional<z.ZodString>;
        instruct: z.ZodOptional<z.ZodString>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
        language: z.ZodOptional<z.ZodString>;
        speed: z.ZodOptional<z.ZodNumber>;
        duration: z.ZodOptional<z.ZodNumber>;
        num_step: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strict>;
}, z.core.$strict>], "cmd">;
export declare const Ok: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodLiteral<"ok">;
    result: z.ZodUnknown;
}, z.core.$strict>;
export declare const Err: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodLiteral<"err">;
    error: z.ZodString;
}, z.core.$strict>;
export declare const Res: z.ZodDiscriminatedUnion<[z.ZodObject<{
    id: z.ZodString;
    type: z.ZodLiteral<"ok">;
    result: z.ZodUnknown;
}, z.core.$strict>, z.ZodObject<{
    id: z.ZodString;
    type: z.ZodLiteral<"err">;
    error: z.ZodString;
}, z.core.$strict>], "type">;
export type VoiceWorkerReq = z.infer<typeof Req>;
export type VoiceWorkerRes = z.infer<typeof Res>;
export type VoiceWorkerStatus = z.infer<typeof Status>;
export type VoiceWorkerTranscribe = z.infer<typeof TranscribeOutput>;
export type VoiceWorkerSynthesize = {
    mime: string;
    sample_rate: number;
    duration_ms: number;
    text_used: string;
    audio: string;
    meta?: unknown;
};
